name: Maven build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        check-latest: true
    - name: Build with Maven
      run: mvn package --file pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: Release
        path: '*'
